version: 2.1
    
jobs:
  test:
    parameters:
      img:
        type: string
    machine:
      image: << parameters.img >>
    resource_class: medium
    environment:
      GOPATH: /home/circleci/.go_workspace
      PATH: /home/circleci/.go_workspace/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      IMPORT_PATH: github.com/ebisol/ebica-api
    working_directory: ~/ebica-api
    steps:
      - checkout
      - run:
          name: debug
          command: |
            echo $GOPATH
            echo $IMPORT_PATH
            echo $HOME
            echo $PYENV_ROOT
            
      - run:
          name: make go path
          command: |
            set -x
            sudo apt-get install rsync
            wget https://dl.google.com/go/go1.17.3.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.17.3.linux-amd64.tar.gz
            mkdir -p "${GOPATH}/src/${IMPORT_PATH}"
            
            
            # rsync -azC --delete $HOME/$CIRCLE_PROJECT_REPONAME/ $GOPATH/src/$IMPORT_PATH/
            go version

  test2:
    machine: true
    resource_class: medium
    environment:
      GOPATH: /home/circleci/.go_workspace
      PATH: /home/circleci/.go_workspace/bin:/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      IMPORT_PATH: github.com/ebisol/ebica-api
    working_directory: ~/ebica-api
    steps:
      - checkout
      - run:
          name: debug
          command: |
            echo $GOPATH
            echo $IMPORT_PATH
            echo $HOME
            echo $PYENV_ROOT
            
      - run:
          name: make go path
          command: |
            set -x
            sudo apt-get install rsync
            wget https://dl.google.com/go/go1.17.3.linux-amd64.tar.gz
            sudo rm -rf /usr/local/go
            sudo tar -C /usr/local -xzf go1.17.3.linux-amd64.tar.gz
            mkdir -p "${GOPATH}/src/${IMPORT_PATH}"
            
            
            # rsync -azC --delete $HOME/$CIRCLE_PROJECT_REPONAME/ $GOPATH/src/$IMPORT_PATH/
            go version

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              img:
                - circleci/classic:201707-01
                - ubuntu-2004:202201-02
      - test2
